# Generated by Django 5.2.17 on 2026-08-23 11:04

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("library", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("question", "Question"),
                            ("revealed", "Revealed"),
                            ("completed", "Completed"),
                            ("expired", "Expired"),
                        ],
                        default="question",
                        max_length=16,
                    ),
                ),
                ("excerpt_start_ms", models.PositiveBigIntegerField()),
                ("excerpt_duration_ms", models.PositiveIntegerField()),
                ("frontier_snapshot_ms", models.PositiveBigIntegerField()),
                ("challenge_level_snapshot", models.PositiveSmallIntegerField()),
                ("submitted_answer", models.CharField(blank=True, max_length=256)),
                ("normalized_answer", models.CharField(blank=True, max_length=256)),
                ("answer_accepted", models.BooleanField(blank=True, null=True)),
                ("matched_answer", models.CharField(blank=True, max_length=256)),
                ("replay_count", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("revealed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_sessions",
                        to="library.part",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("reviewed_at", models.DateTimeField(db_index=True)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Again"), (2, "Hard"), (3, "Good"), (4, "Easy")]
                    ),
                ),
                ("submitted_answer", models.CharField(max_length=256)),
                ("normalized_answer", models.CharField(max_length=256)),
                ("answer_accepted", models.BooleanField()),
                ("matched_answer", models.CharField(blank=True, max_length=256)),
                ("replay_count", models.PositiveSmallIntegerField(default=0)),
                ("excerpt_start_ms", models.PositiveBigIntegerField()),
                ("excerpt_duration_ms", models.PositiveIntegerField()),
                ("scheduler_before", models.TextField(blank=True)),
                ("scheduler_after", models.TextField()),
                ("fsrs_review_log", models.TextField()),
                ("challenge_before", models.JSONField()),
                ("challenge_after", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_logs",
                        to="library.part",
                    ),
                ),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_log",
                        to="reviews.reviewsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-reviewed_at"],
            },
        ),
        migrations.CreateModel(
            name="StudyState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("fsrs_card_json", models.TextField(blank=True)),
                ("due_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("last_review_at", models.DateTimeField(blank=True, null=True)),
                ("challenge_level", models.PositiveSmallIntegerField(default=0)),
                ("frontier_ms", models.PositiveBigIntegerField(default=60000)),
                ("success_credit", models.PositiveSmallIntegerField(default=0)),
                ("reviews_at_level", models.PositiveIntegerField(default=0)),
                ("review_count", models.PositiveIntegerField(default=0)),
                ("lapse_count", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "part",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="study_state",
                        to="library.part",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="reviewsession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("stage__in", ["question", "revealed"])),
                fields=("owner",),
                name="one_open_review_per_owner",
            ),
        ),
        migrations.AddIndex(
            model_name="reviewlog",
            index=models.Index(
                fields=["owner", "part", "-reviewed_at"], name="reviews_rev_owner_i_909540_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="studystate",
            constraint=models.UniqueConstraint(
                fields=("owner", "part"), name="unique_study_state_per_part"
            ),
        ),
        migrations.AddConstraint(
            model_name="studystate",
            constraint=models.CheckConstraint(
                condition=models.Q(("challenge_level__lte", 5)),
                name="challenge_level_between_zero_and_five",
            ),
        ),
    ]
